version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_emails
    ports:
      - 5432:5432
  mail-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
